### ISSUE TITLE
Compilation error after upgrading N2CMS.Mvc to version 2.9.6.11

### ISSUE THREAD

**Issue by laurachan** [n2cms/n2cms#740]
If I install the latest version of the N2CMS.Mvc package on a project, I get the following compilation error:

The type or namespace name 'Slideshow' could not be found (are you missing a using directive or an assembly reference?)

Occurs in ContentPartsController.cs lines 22 and 23. It was fine in N2CMS 2.9.6.8 and before.

Thanks.

**Comment by bherila** [comment]
This should be fixed now @laurachan , can you confirm please?

**Comment by jfaquinojr** [comment]
got the latest nuget package. this is still there.

**Comment by bherila** [comment]
Try installing `N2CMS.ReusableParts`

**Comment by krishie** [comment]
Sorry 'bherila', it's still the same - looking at the code base, it seems it's in 'N2.Web' namespace, but looking at 'Object Browser', couldn't find the same. I'm using v2.9.6.17.

**Comment by devBarn** [comment]
I'm afraid it is the same in 2.9.6.17. Ben do you have a fix for this you can share?

**Comment by bherila** [comment]
I cannot reproduce the issue, can you make a .zip of your sln and send it to me at ben -at herila dot net

**Comment by devBarn** [comment]
Hello again, I'm afraid I've found that this was in the N2CMS.Dinamico 2.9.6.17 NuGet package not the N2CMS.MVC one. Do you want me to start a new issue?

**Comment by bherila** [comment]
I don't think so, it sounds likely to be the same issue.

**Comment by devBarn** [comment]
Has there been any movement on this? Am I better off installing an earlier version?

**Comment by bherila** [comment]
I will not be releasing any new packages until someone is able to make N2 build on VS 2017. So if that will fix your issue, I recommend going that route 👍

**Comment by devBarn** [comment]
Do you mean build for regular development or build for contributing to the source? I'm pretty sure I got the former working yesterday.

**Comment by bherila** [comment]
Build for compiling the N2 packages, I mean, namely the build.bat and nugetbuild.bat and n2.proj file inside the build folder here.

**Comment by minajevs** [comment]
It is still not working for me on v2.9.6.19. 
Any workarounds or ETA on a fix?

**Comment by matthewvukomanovic** [comment]
Looks like the reusable parts nuget package doesn't contain the dll which is why it's then not compiling.

**Comment by laurachan** [comment]
I think I can confirm what @matthewvukomanovic said--as soon as I try to upgrade N2CMS.ReusableParts to version 2.9.6.19 (without touching N2CMS.Mvc or N2CMS.Dinamico), the compilation error in ContentPartsController regarding the Slideshow part will appear when I attempt to compile my project.
